/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/appointments` | `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/records` | `/records`; params?: Router.UnknownInputParams; } | { pathname: `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/book/step1`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/book/step2`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/book/step3`; params?: Router.UnknownInputParams; } | { pathname: `/records/form`; params?: Router.UnknownInputParams; } | { pathname: `/records`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/appointments` | `/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/records` | `/records`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/book/step1`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/book/step2`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/book/step3`; params?: Router.UnknownOutputParams; } | { pathname: `/records/form`; params?: Router.UnknownOutputParams; } | { pathname: `/records`; params?: Router.UnknownOutputParams; } | { pathname: `/appointments/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/appointments${`?${string}` | `#${string}` | ''}` | `/appointments${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/records${`?${string}` | `#${string}` | ''}` | `/records${`?${string}` | `#${string}` | ''}` | `/appointments${`?${string}` | `#${string}` | ''}` | `/appointments/book/step1${`?${string}` | `#${string}` | ''}` | `/appointments/book/step2${`?${string}` | `#${string}` | ''}` | `/appointments/book/step3${`?${string}` | `#${string}` | ''}` | `/records/form${`?${string}` | `#${string}` | ''}` | `/records${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/appointments` | `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/records` | `/records`; params?: Router.UnknownInputParams; } | { pathname: `/appointments`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/book/step1`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/book/step2`; params?: Router.UnknownInputParams; } | { pathname: `/appointments/book/step3`; params?: Router.UnknownInputParams; } | { pathname: `/records/form`; params?: Router.UnknownInputParams; } | { pathname: `/records`; params?: Router.UnknownInputParams; } | `/appointments/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/appointments/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
